### ISSUE TITLE
Invalid url

### ISSUE THREAD

**Issue by dankinsoid** [apple/swift-http-types#46]
HTTPRequest always adds a `/` after the host, sometimes leading to invalid URLs.
```swift
let request = HTTPRequest(url:  URL(string: "https://example.com?page=some")!)
XCTAssertEqual(request.url!.absoluteString, "https://example.com?page=some")
// XCTAssertEqual failed: ("https://example.com/?page=some") is not equal to ("https://example.com?page=some")
```
I'm not sure if "https://example.com/?page=some" is an invalid URL, but I have experienced some servers returning errors for requests with "/?". 
There is also another unexpected behavior:
```swift
let request = HTTPRequest(url:  URL(string: "https://example.com")!)
XCTAssertEqual(request.url!.absoluteString, "https://example.com")
// XCTAssertEqual failed: ("https://example.com/") is not equal to ("https://example.com")
```
I would not expect my URL to be altered in any way by HTTPRequest.

**Comment by dankinsoid** [comment]
I'm curious why you use pseudo headers instead of storing the URL itself. It leads to an unintuitive API.

**Comment by guoye-zhang** [comment]
This is a standard normalization done by all browsers:

https://www.rfc-editor.org/rfc/rfc9110.html#section-4.2.3-4.2

A request typically requires a path, e.g. `GET / HTTP/1.1`.

**Comment by guoye-zhang** [comment]
Currently URL is provided purely as a convenience since it's immediately decomposed into request components. The reasons are twofold:

1. The full URL isn't what's sent in the request. The type is intended to be low level and represent exactly what's transferred on the wire. Some information on the URL is lost (username, password, fragment) but the request you sent will be exactly what's received on the server.
2. Some projects might not want to depend on Foundation, so the base types don't have any Foundation dependencies. This concern will likely be resolved by the new Swift Foundation when that becomes the default.

**Comment by dankinsoid** [comment]
@guoye-zhang some backends cannot parse this combination "/?"; there must be a way to customize it

**Comment by guoye-zhang** [comment]
While you can customize it by setting the `path` on the request directly, I suggest fixing the backend instead. If it's expecting a bare `?`, it wouldn't work with URLSession, curl, or any browsers. I suspect a lot more backends cannot parse a path starting with `?` without `/`.

You can confirm the behavior of clients using `nc -l 8080`, and in a separate terminal window run e.g. `curl "http://localhost:8080?q=1"`. Is there any HTTP client that doesn't add a slash?

**Comment by dankinsoid** [comment]
@guoye-zhang thank you very much, setting the path is working. Im unable to fix the backend, because it's not mine, it's a yandex API.
